"use client"

import React from 'react'
import { useOrchestrationStore } from '../../store/useOrchestrationStore'
import { Circle, Timer, CheckCircle2 } from 'lucide-react'

export function SprintBoard() {
  // Read the live backlog generated by the PM Agent
  const { backlog } = useOrchestrationStore()
  const tasks = backlog?.tasks || []

  if (tasks.length === 0) {
    return (
      <div className="flex-1 w-full flex flex-col items-center justify-center border border-dashed border-white/5 rounded-2xl bg-white/[0.01] p-12 text-center min-h-[40vh]">
        <span className="w-5 h-5 border-2 border-emerald-500 border-t-transparent rounded-full animate-spin mb-4" />
        <p className="font-mono text-xs text-neutral-500">PM Agent is drafting agile sprint tickets...</p>
      </div>
    )
  }

  // Group the dynamic tasks by their status
  const todoTasks = tasks.filter(t => t.status.toLowerCase().includes('todo') || t.status.toLowerCase().includes('backlog'))
  const inProgressTasks = tasks.filter(t => t.status.toLowerCase().includes('progress'))
  const doneTasks = tasks.filter(t => t.status.toLowerCase().includes('done'))

  return (
    <div className="w-full h-full p-6 overflow-y-auto">
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-6xl mx-auto">
        
        {/* TO DO COLUMN */}
        <div className="space-y-4">
          <div className="flex items-center space-x-2 text-neutral-400 font-mono text-[10px] uppercase tracking-widest border-b border-white/5 pb-2">
            <Circle className="w-3 h-3" /> <span>To Do ({todoTasks.length})</span>
          </div>
          {todoTasks.map(task => (
            <div key={task.id} className="p-4 rounded-xl border border-white/5 bg-[#09090f]/60 backdrop-blur-md space-y-3">
              <div className="flex justify-between items-start">
                <span className="text-[9px] font-mono text-neutral-500">{task.id}</span>
                <span className="text-[9px] px-1.5 py-0.5 rounded bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">{task.assignee}</span>
              </div>
              <p className="text-xs text-neutral-300 font-sans leading-relaxed">{task.title}</p>
            </div>
          ))}
        </div>

        {/* IN PROGRESS COLUMN */}
        <div className="space-y-4">
          <div className="flex items-center space-x-2 text-amber-400 font-mono text-[10px] uppercase tracking-widest border-b border-white/5 pb-2">
            <Timer className="w-3 h-3" /> <span>In Progress ({inProgressTasks.length})</span>
          </div>
          {inProgressTasks.map(task => (
            <div key={task.id} className="p-4 rounded-xl border border-white/5 bg-[#09090f]/60 backdrop-blur-md space-y-3">
              <div className="flex justify-between items-start">
                <span className="text-[9px] font-mono text-neutral-500">{task.id}</span>
                <span className="text-[9px] px-1.5 py-0.5 rounded bg-amber-500/10 text-amber-400 border border-amber-500/20">{task.assignee}</span>
              </div>
              <p className="text-xs text-neutral-300 font-sans leading-relaxed">{task.title}</p>
            </div>
          ))}
        </div>

        {/* DONE COLUMN */}
        <div className="space-y-4">
          <div className="flex items-center space-x-2 text-sky-400 font-mono text-[10px] uppercase tracking-widest border-b border-white/5 pb-2">
            <CheckCircle2 className="w-3 h-3" /> <span>Completed ({doneTasks.length})</span>
          </div>
          {doneTasks.map(task => (
            <div key={task.id} className="p-4 rounded-xl border border-white/5 bg-[#09090f]/60 backdrop-blur-md space-y-3 opacity-50">
              <div className="flex justify-between items-start">
                <span className="text-[9px] font-mono text-neutral-500">{task.id}</span>
                <span className="text-[9px] px-1.5 py-0.5 rounded bg-sky-500/10 text-sky-400 border border-sky-500/20">{task.assignee}</span>
              </div>
              <p className="text-xs text-neutral-300 font-sans leading-relaxed line-through">{task.title}</p>
            </div>
          ))}
        </div>

      </div>
    </div>
  )
}